# Generated by Django 3.2 on 2021-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210530_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
