# Generated by Django 3.2 on 2021-05-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
    ]
