# Generated by Django 3.2 on 2021-05-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_review_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
