# Generated by Django 3.2 on 2021-06-03 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 3, 18, 44, 48, 234508, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
