# Generated by Django 3.2 on 2021-05-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_rating',
        ),
    ]
