# Generated by Django 3.2 on 2021-06-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_wishlist_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='added_date',
        ),
    ]
